joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10 
front_right_wheel_joint :
  type : joint_state_controller/JointStateController
  pid : {p : 0.0, i : 0.0, d : 0.0}

front_left_wheel_joint :
  type : joint_state_controller/JointStateController
  pid : {p : 0.0, i : 0.0, d : 0.0}
